#define SETTINGS_COUNT 6

/* RFC 7540: Section 6.5.2 */
static const char *settings_ids[] = { NULL, "SETTINGS_HEADER_TABLE_SIZE", "SETTINGS_ENABLE_PUSH", "SETTINGS_MAX_CONCURRENT_STREAMS", "SETTINGS_INITIAL_WINDOW_SIZE", "SETTINGS_MAX_FRAME_SIZE", "SETTINGS_MAX_HEADER_LIST_SIZE" };
/* RFC 7540: Section 6.x */
static const char *frame_types[] = { "DATA", "HEADERS", "PRIORITY", "RST_STREAM", "SETTINGS", "PUSH_PROMISE", "PING", "GOAWAY", "WINDOW_UPDATE", "CONTINUATION" };
/* RFC 7540: Section 7 */
static const char *error_codes[] = { "NO_ERROR", "PROTOCOL_ERROR", "INTERNAL_ERROR", "FLOW_CONTROL_ERROR", "SETTINGS_TIMEOUT", "STREAM_CLOSED", "FRAME_SIZE_ERROR", "REFUSED_SIZE", "CANCEL", "COMPRESSION_ERROR", "CONNECT_ERROR", "ENHANCE_YOUR_CALM", "INADEQUATE_SECURITY", "HTTP_1_REQUIRED" };

typedef enum {
	H2_NO_ERROR = 0x0,
	H2_PROTOCOL_ERROR = 0x1,
	H2_INTERNAL_ERROR = 0x2,
	H2_FLOW_CONTROL_ERROR = 0x3,
	H2_SETTINGS_TIMEOUT = 0x4,
	H2_STREAM_CLOSED = 0x5,
	H2_FRAME_SIZE_ERROR = 0x6,
	H2_REFUSED_STREAM = 0x7,
	H2_CANCEL = 0x8,
	H2_COMPRESSION_ERROR = 0x9,
	H2_CONNECT_ERROR = 0xA,
	H2_ENHANCE_YOUR_CALM = 0xB,
	H2_INADEQUATE_SECURITY = 0xC,
	H2_HTTP_1_1_REQUIRED = 0xD
} H2_ERROR;

#define FLAG_ACK 0x1
#define FLAG_END_STREAM 0x1
#define FLAG_END_HEADER 0x4
#define FLAG_PADDED 0x8
#define FLAG_PRIORITY 0x20

static const char *preface = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n";


/* util functions */
static uint32_t u32(const char *arr) {
	return (arr[0] << 24) | (arr[1] << 16) | (arr[2] << 8) | arr[3];
}
#define PRTERR(text) fprintf(stderr, "\x1b[31m%s\x1b[0m", text)
#define BITS31 0xEFFFFFFF
